# Generated by Django 2.1.7 on 2019-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
